# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import simqueue.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('command', models.CharField(blank=True, max_length=200)),
                ('collab_id', models.TextField(max_length=25)),
                ('user_id', models.CharField(default=b'me', max_length=25)),
                ('status', models.CharField(blank=True, choices=[(b'submitted', b'submitted'), (b'validated', b'validated'), (b'running', b'running'), (b'mapped', b'mapped'), (b'finished', b'finished'), (b'error', b'error'), (b'removed', b'removed')], default=b'submitted', max_length=15)),
                ('hardware_platform', models.CharField(max_length=20)),
                ('hardware_config', jsonfield.fields.JSONField(blank=True, null=True)),
                ('timestamp_submission', models.DateTimeField(blank=True, default=simqueue.models.now_in_utc)),
                ('timestamp_completion', models.DateTimeField(blank=True, null=True)),
                ('provenance', jsonfield.fields.JSONField(blank=True, null=True)),
                ('resource_usage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='simqueue.Job')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='input_data',
            field=models.ManyToManyField(blank=True, related_name='input_to', to='simqueue.DataItem'),
        ),
        migrations.AddField(
            model_name='job',
            name='output_data',
            field=models.ManyToManyField(blank=True, related_name='generated_by', to='simqueue.DataItem'),
        ),
    ]
