# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('context', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('collab', models.CharField(help_text=b'Collab id', max_length=32)),
                ('owner', models.CharField(help_text=b'HBP user id', max_length=32)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('abstract', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text=b'Requested/granted duration in days')),
                ('start_date', models.DateField(blank=True, help_text=b'Value set when project is accepted', null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, help_text=b'Value set when project is accepted/refused', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text=b'HBP user id', max_length=15)),
                ('approved_by', models.CharField(help_text=b'HBP user id', max_length=15)),
                ('approved_on', models.DateTimeField(help_text=b'If null, applicant has not been approved', null=True)),
                ('platform', models.CharField(help_text=b'System to which approval applies', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=15)),
                ('limit', models.FloatField(help_text=b'Quantity of resources granted')),
                ('usage', models.FloatField(help_text=b'Quantity of resources used')),
                ('platform', models.CharField(help_text=b'System to which quota applies', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotas.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(help_text=b'HBP user id', max_length=15)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[(b'technical', b'technical'), (b'scientific', b'scientific')], max_length=10)),
                ('date_due', models.DateField(help_text=b'Date when review due')),
                ('date_completed', models.DateField(help_text=b'Date when review submitted')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotas.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to='quotas.ProjectMember'),
        ),
    ]
